var Productos = [
    {
      Id: 0,
      Nicho: "Hogar",
      Nombre: "Lamparas De Mesa Metalica Touch Winner",
      Precio: 20000,
      PrecioTEXTO: "$20.000",
      Stock: 600,
      Cantidad: 0,
      Colores: {
        Blanco: {
          cantidad: 200,
          imagen: "Imagen De los Productos/Hogar/1712175860414YtLo7xhL._AC_SY879_ (1).webp",
          imagenRespaldo: "Imagen De los Productos/Hogar/1712175860414YtLo7xhL._AC_SY879_ (1).png",
          Img1: "Imagen De los Productos/Hogar/imagen.png",
          ImgRespaldo2: "Imagen De los Productos/Hogar/naranja.png",
        },
        Gold: {
          cantidad: 200,
          imagen: "Imagen De los Productos/Hogar/171217586041EZLpmVyuL._AC_SY879_ (2).png",
          imagenRespaldo: "Imagen De los Productos/Hogar/171217586041EZLpmVyuL._AC_SY879_ (2).webp",
          Img1: "Imagen De los Productos/Hogar/imagen.png",
          ImgRespaldo2: "Imagen De los Productos/Hogar/naranja.png",
          ImgRespaldo3: "Imagen De los Productos/Hogar/oro.jpeg",
        },
        //Negro: {
          //cantidad: 200,
        //}
      },
      rutaImagen: {
        Img0: "Imagen De los Productos/Hogar/171217586051dF9lKnpFL._AC_SX679_.webp",
        ImgRespaldo0: "Imagen De los Productos/Hogar/171217586051dF9lKnpFL._AC_SX679_.png",
        Img1: "Imagen De los Productos/Hogar/imagen.webp",
        ImgRespaldo1: "Imagen De los Productos/Hogar/imagen.png",
        Img2: "Imagen De los Productos/Hogar/naranja.webp",
        ImgRespaldo2: "Imagen De los Productos/Hogar/naranja.png",

      },
      Descripcion: {
        descripcion1: "¡Transforma la atmósfera de tu hogar con nuestra lámpara touch de metal, la combinación perfecta de estilo, funcionalidad y comodidad!",
        descripcion2: "¿Buscas añadir un toque de elegancia y funcionalidad a tu espacio? Nuestra lámpara touch de metal es justo lo que necesitas. Ofrece un brillo suave y agradable que ilumina la habitación sin causar deslumbramientos.",
        descripcion3: "Pero eso no es todo. Imagina cómo este diseño elegante puede transformar tu hogar. Con su aspecto industrial y estética moderna, nuestra lámpara añade un toque de sofisticación a cualquier habitación. Desde la sala de estar hasta el dormitorio, esta lámpara se convierte en el centro de atención con su estilo único.",
        descripcion4: "¿Te gustaría tener una iluminación práctica y elegante en tu hogar? Nuestra lámpara no solo es elegante, sino también funcional. Su varrucción simple y elegante se adapta a cualquier espacio, ya sea en una mesa auxiliar, escritorio o mesita de noche. Además, la pantalla de protección ocular filtra la luz de manera óptima, eliminando la fatiga ocular y protegiendo tus ojos mientras disfrutas de la iluminación perfecta.",
        descripcion5: "¿Listo para experimentar la combinación perfecta de estilo y funcionalidad en tu hogar? ¡No esperes más! Nuestra garantía de satisfacción del 100% garantiza que estaremos aquí para ti antes y después de tu compra, para asegurarnos de que tu experiencia sea inigualable. Haz clic ahora mismo y lleva a casa la lámpara touch de metal que transformará tu hogar en un santuario de estilo y confort. ¡No te lo pierdas!",
      },
    },
    {
      Id: 1,
      Nicho: "Hogar",
      Nombre: "Lampara De Velador Para Mesa",
      Precio: 15000,
      PrecioTEXTO: "$15.000",
      Stock: 50,
      Cantidad: 0,
      rutaImagen: {
        Img0: "Imagen De los Productos/Hogar/1702435337DSC09764-600x600.webp",
        ImgRespaldo0: "Imagen De los Productos/Hogar/1702435337DSC09764-600x600.png",
        Img1: "Imagen De los Productos/Hogar/1702435337LAMPARA-FLORES-03-600x600.webp",
        ImgRespaldo1: "Imagen De los Productos/Hogar/1702435337LAMPARA-FLORES-03-600x600.png",
      },
      Descripcion: {
        descripcion1: "Lámparas de mesa decorativas y elegante, diseño minimalista, modelo diferente",
        descripcion2: "Modelo: Lampara de mesa 21227",
        descripcion3: "Usa bombilla E14",
        descripcion4: "Voltaje: 220V",
        descripcion5: "Medidas: 10x10x26.5cm",
        descripcion6: "Tecnología de iluminación: Incandescente",
        descripcion7: "Material de la estructura: Loza",
        descripcion8: "Material de la pantalla: Tela",
      },
      Caracteristicas: {
        caracteristica0: "Voltaje: 220V",
        caracteristica1: "Usa bombilla E14",
        caracteristica2: "Medidas: 10x10x26.5cm",
        caracteristica3: "Voltaje: 220V",
        caracteristica4: "Voltaje: 220V",
        caracteristica5: "Voltaje: 220V",
        caracteristica6: "Voltaje: 220V",
        caracteristica7: "Voltaje: 220V",
        caracteristica8: "Voltaje: 220V",
        caracteristica9: "Voltaje: 220V",
        caracteristica10: "Voltaje: 220V",
        caracteristica11: "Voltaje: 220V",
        caracteristica12: "Voltaje: 220V",
        caracteristica13: "Voltaje: 220V",
        caracteristica14: "Voltaje: 220V",
      },
    },
];  